// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/api/billing.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "google/api/Billing.pbobjc.h"
 #import "google/api/Annotations.pbobjc.h"
 #import "google/api/Metric.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - BillingRoot

@implementation BillingRoot

+ (GPBExtensionRegistry*)extensionRegistry {
  // This is called by +initialize so there is no need to worry
  // about thread safety and initialization of registry.
  static GPBExtensionRegistry* registry = nil;
  if (!registry) {
    GPBDebugCheckRuntimeVersion();
    registry = [[GPBExtensionRegistry alloc] init];
    [registry addExtensions:[AnnotationsRoot extensionRegistry]];
    [registry addExtensions:[MetricRoot extensionRegistry]];
  }
  return registry;
}

@end

#pragma mark - BillingRoot_FileDescriptor

static GPBFileDescriptor *BillingRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPBDebugCheckRuntimeVersion();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"google.api"
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - Billing

@implementation Billing

@dynamic metricsArray, metricsArray_Count;
@dynamic rulesArray, rulesArray_Count;

typedef struct Billing__storage_ {
  uint32_t _has_storage_[1];
  NSMutableArray *metricsArray;
  NSMutableArray *rulesArray;
} Billing__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "metricsArray",
        .dataTypeSpecific.className = NULL,
        .number = Billing_FieldNumber_MetricsArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(Billing__storage_, metricsArray),
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "rulesArray",
        .dataTypeSpecific.className = GPBStringifySymbol(BillingStatusRule),
        .number = Billing_FieldNumber_RulesArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(Billing__storage_, rulesArray),
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[Billing class]
                                     rootClass:[BillingRoot class]
                                          file:BillingRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(Billing__storage_)
                                         flags:0];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - BillingStatusRule

@implementation BillingStatusRule

@dynamic selector;
@dynamic allowedStatusesArray, allowedStatusesArray_Count;

typedef struct BillingStatusRule__storage_ {
  uint32_t _has_storage_[1];
  NSString *selector;
  NSMutableArray *allowedStatusesArray;
} BillingStatusRule__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "selector",
        .dataTypeSpecific.className = NULL,
        .number = BillingStatusRule_FieldNumber_Selector,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(BillingStatusRule__storage_, selector),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "allowedStatusesArray",
        .dataTypeSpecific.className = NULL,
        .number = BillingStatusRule_FieldNumber_AllowedStatusesArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(BillingStatusRule__storage_, allowedStatusesArray),
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[BillingStatusRule class]
                                     rootClass:[BillingRoot class]
                                          file:BillingRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(BillingStatusRule__storage_)
                                         flags:0];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
