// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/api/metric.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "google/api/Metric.pbobjc.h"
 #import "google/api/Label.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - MetricRoot

@implementation MetricRoot

+ (GPBExtensionRegistry*)extensionRegistry {
  // This is called by +initialize so there is no need to worry
  // about thread safety and initialization of registry.
  static GPBExtensionRegistry* registry = nil;
  if (!registry) {
    GPBDebugCheckRuntimeVersion();
    registry = [[GPBExtensionRegistry alloc] init];
    [registry addExtensions:[LabelRoot extensionRegistry]];
  }
  return registry;
}

@end

#pragma mark - MetricRoot_FileDescriptor

static GPBFileDescriptor *MetricRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPBDebugCheckRuntimeVersion();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"google.api"
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - MetricDescriptor

@implementation MetricDescriptor

@dynamic name;
@dynamic type;
@dynamic labelsArray, labelsArray_Count;
@dynamic metricKind;
@dynamic valueType;
@dynamic unit;
@dynamic description_p;
@dynamic displayName;

typedef struct MetricDescriptor__storage_ {
  uint32_t _has_storage_[1];
  MetricDescriptor_MetricKind metricKind;
  MetricDescriptor_ValueType valueType;
  NSString *name;
  NSMutableArray *labelsArray;
  NSString *unit;
  NSString *description_p;
  NSString *displayName;
  NSString *type;
} MetricDescriptor__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "name",
        .dataTypeSpecific.className = NULL,
        .number = MetricDescriptor_FieldNumber_Name,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(MetricDescriptor__storage_, name),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "labelsArray",
        .dataTypeSpecific.className = GPBStringifySymbol(LabelDescriptor),
        .number = MetricDescriptor_FieldNumber_LabelsArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(MetricDescriptor__storage_, labelsArray),
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "metricKind",
        .dataTypeSpecific.enumDescFunc = MetricDescriptor_MetricKind_EnumDescriptor,
        .number = MetricDescriptor_FieldNumber_MetricKind,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(MetricDescriptor__storage_, metricKind),
        .flags = GPBFieldOptional | GPBFieldHasEnumDescriptor,
        .dataType = GPBDataTypeEnum,
      },
      {
        .name = "valueType",
        .dataTypeSpecific.enumDescFunc = MetricDescriptor_ValueType_EnumDescriptor,
        .number = MetricDescriptor_FieldNumber_ValueType,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(MetricDescriptor__storage_, valueType),
        .flags = GPBFieldOptional | GPBFieldHasEnumDescriptor,
        .dataType = GPBDataTypeEnum,
      },
      {
        .name = "unit",
        .dataTypeSpecific.className = NULL,
        .number = MetricDescriptor_FieldNumber_Unit,
        .hasIndex = 4,
        .offset = (uint32_t)offsetof(MetricDescriptor__storage_, unit),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "description_p",
        .dataTypeSpecific.className = NULL,
        .number = MetricDescriptor_FieldNumber_Description_p,
        .hasIndex = 5,
        .offset = (uint32_t)offsetof(MetricDescriptor__storage_, description_p),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "displayName",
        .dataTypeSpecific.className = NULL,
        .number = MetricDescriptor_FieldNumber_DisplayName,
        .hasIndex = 6,
        .offset = (uint32_t)offsetof(MetricDescriptor__storage_, displayName),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "type",
        .dataTypeSpecific.className = NULL,
        .number = MetricDescriptor_FieldNumber_Type,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(MetricDescriptor__storage_, type),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[MetricDescriptor class]
                                     rootClass:[MetricRoot class]
                                          file:MetricRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(MetricDescriptor__storage_)
                                         flags:0];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

int32_t MetricDescriptor_MetricKind_RawValue(MetricDescriptor *message) {
  GPBDescriptor *descriptor = [MetricDescriptor descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:MetricDescriptor_FieldNumber_MetricKind];
  return GPBGetMessageInt32Field(message, field);
}

void SetMetricDescriptor_MetricKind_RawValue(MetricDescriptor *message, int32_t value) {
  GPBDescriptor *descriptor = [MetricDescriptor descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:MetricDescriptor_FieldNumber_MetricKind];
  GPBSetInt32IvarWithFieldInternal(message, field, value, descriptor.file.syntax);
}

int32_t MetricDescriptor_ValueType_RawValue(MetricDescriptor *message) {
  GPBDescriptor *descriptor = [MetricDescriptor descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:MetricDescriptor_FieldNumber_ValueType];
  return GPBGetMessageInt32Field(message, field);
}

void SetMetricDescriptor_ValueType_RawValue(MetricDescriptor *message, int32_t value) {
  GPBDescriptor *descriptor = [MetricDescriptor descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:MetricDescriptor_FieldNumber_ValueType];
  GPBSetInt32IvarWithFieldInternal(message, field, value, descriptor.file.syntax);
}

#pragma mark - Enum MetricDescriptor_MetricKind

GPBEnumDescriptor *MetricDescriptor_MetricKind_EnumDescriptor(void) {
  static GPBEnumDescriptor *descriptor = NULL;
  if (!descriptor) {
    static const char *valueNames =
        "MetricKindUnspecified\000Gauge\000Delta\000Cumula"
        "tive\000";
    static const int32_t values[] = {
        MetricDescriptor_MetricKind_MetricKindUnspecified,
        MetricDescriptor_MetricKind_Gauge,
        MetricDescriptor_MetricKind_Delta,
        MetricDescriptor_MetricKind_Cumulative,
    };
    GPBEnumDescriptor *worker =
        [GPBEnumDescriptor allocDescriptorForName:GPBNSStringifySymbol(MetricDescriptor_MetricKind)
                                       valueNames:valueNames
                                           values:values
                                            count:(uint32_t)(sizeof(values) / sizeof(int32_t))
                                     enumVerifier:MetricDescriptor_MetricKind_IsValidValue];
    if (!OSAtomicCompareAndSwapPtrBarrier(nil, worker, (void * volatile *)&descriptor)) {
      [worker release];
    }
  }
  return descriptor;
}

BOOL MetricDescriptor_MetricKind_IsValidValue(int32_t value__) {
  switch (value__) {
    case MetricDescriptor_MetricKind_MetricKindUnspecified:
    case MetricDescriptor_MetricKind_Gauge:
    case MetricDescriptor_MetricKind_Delta:
    case MetricDescriptor_MetricKind_Cumulative:
      return YES;
    default:
      return NO;
  }
}

#pragma mark - Enum MetricDescriptor_ValueType

GPBEnumDescriptor *MetricDescriptor_ValueType_EnumDescriptor(void) {
  static GPBEnumDescriptor *descriptor = NULL;
  if (!descriptor) {
    static const char *valueNames =
        "ValueTypeUnspecified\000Bool\000Int64\000Double\000S"
        "tring\000Distribution\000Money\000";
    static const int32_t values[] = {
        MetricDescriptor_ValueType_ValueTypeUnspecified,
        MetricDescriptor_ValueType_Bool,
        MetricDescriptor_ValueType_Int64,
        MetricDescriptor_ValueType_Double,
        MetricDescriptor_ValueType_String,
        MetricDescriptor_ValueType_Distribution,
        MetricDescriptor_ValueType_Money,
    };
    GPBEnumDescriptor *worker =
        [GPBEnumDescriptor allocDescriptorForName:GPBNSStringifySymbol(MetricDescriptor_ValueType)
                                       valueNames:valueNames
                                           values:values
                                            count:(uint32_t)(sizeof(values) / sizeof(int32_t))
                                     enumVerifier:MetricDescriptor_ValueType_IsValidValue];
    if (!OSAtomicCompareAndSwapPtrBarrier(nil, worker, (void * volatile *)&descriptor)) {
      [worker release];
    }
  }
  return descriptor;
}

BOOL MetricDescriptor_ValueType_IsValidValue(int32_t value__) {
  switch (value__) {
    case MetricDescriptor_ValueType_ValueTypeUnspecified:
    case MetricDescriptor_ValueType_Bool:
    case MetricDescriptor_ValueType_Int64:
    case MetricDescriptor_ValueType_Double:
    case MetricDescriptor_ValueType_String:
    case MetricDescriptor_ValueType_Distribution:
    case MetricDescriptor_ValueType_Money:
      return YES;
    default:
      return NO;
  }
}

#pragma mark - Metric

@implementation Metric

@dynamic type;
@dynamic labels, labels_Count;

typedef struct Metric__storage_ {
  uint32_t _has_storage_[1];
  NSMutableDictionary *labels;
  NSString *type;
} Metric__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "labels",
        .dataTypeSpecific.className = NULL,
        .number = Metric_FieldNumber_Labels,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(Metric__storage_, labels),
        .flags = GPBFieldMapKeyString,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "type",
        .dataTypeSpecific.className = NULL,
        .number = Metric_FieldNumber_Type,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(Metric__storage_, type),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[Metric class]
                                     rootClass:[MetricRoot class]
                                          file:MetricRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(Metric__storage_)
                                         flags:0];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
