// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/api/service.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_GEN_VERSION != 30001
#error This file was generated by a different version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class Authentication;
@class Backend;
@class Billing;
@class Context;
@class Control;
@class Documentation;
@class GPBApi;
@class GPBEnum;
@class GPBType;
@class GPBUInt32Value;
@class Http;
@class LogDescriptor;
@class Logging;
@class MetricDescriptor;
@class MonitoredResourceDescriptor;
@class Monitoring;
@class ProjectProperties;
@class SystemParameters;
@class Usage;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - ServiceRoot

/// Exposes the extension registry for this file.
///
/// The base class provides:
/// @code
///   + (GPBExtensionRegistry *)extensionRegistry;
/// @endcode
/// which is a @c GPBExtensionRegistry that includes all the extensions defined by
/// this file and all files that it depends on.
@interface ServiceRoot : GPBRootObject
@end

#pragma mark - Service

typedef GPB_ENUM(Service_FieldNumber) {
  Service_FieldNumber_Name = 1,
  Service_FieldNumber_Title = 2,
  Service_FieldNumber_ApisArray = 3,
  Service_FieldNumber_TypesArray = 4,
  Service_FieldNumber_EnumsArray = 5,
  Service_FieldNumber_Documentation = 6,
  Service_FieldNumber_Backend = 8,
  Service_FieldNumber_HTTP = 9,
  Service_FieldNumber_Authentication = 11,
  Service_FieldNumber_Context = 12,
  Service_FieldNumber_Usage = 15,
  Service_FieldNumber_ProjectProperties = 17,
  Service_FieldNumber_ConfigVersion = 20,
  Service_FieldNumber_Control = 21,
  Service_FieldNumber_ProducerProjectId = 22,
  Service_FieldNumber_LogsArray = 23,
  Service_FieldNumber_MetricsArray = 24,
  Service_FieldNumber_MonitoredResourcesArray = 25,
  Service_FieldNumber_Billing = 26,
  Service_FieldNumber_Logging = 27,
  Service_FieldNumber_Monitoring = 28,
  Service_FieldNumber_SystemParameters = 29,
  Service_FieldNumber_Id_p = 33,
};

/// `Service` is the root object of the configuration schema. It
/// describes basic information like the name of the service and the
/// exposed API interfaces, and delegates other aspects to configuration
/// sub-sections.
///
/// Example:
///
///     type: google.api.Service
///     config_version: 1
///     name: calendar.googleapis.com
///     title: Google Calendar API
///     apis:
///     - name: google.calendar.Calendar
///     backend:
///       rules:
///       - selector: "*"
///         address: calendar.example.com
@interface Service : GPBMessage

/// The version of the service configuration. The config version may
/// influence interpretation of the configuration, for example, to
/// determine defaults. This is documented together with applicable
/// options. The current default for the config version itself is `3`.
@property(nonatomic, readwrite, strong, null_resettable) GPBUInt32Value *configVersion;
/// Test to see if @c configVersion has been set.
@property(nonatomic, readwrite) BOOL hasConfigVersion;

/// The DNS address at which this service is available,
/// e.g. `calendar.googleapis.com`.
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

/// A unique ID for a specific instance of this message, typically assigned
/// by the client for tracking purpose. If empty, the server may choose to
/// generate one instead.
@property(nonatomic, readwrite, copy, null_resettable) NSString *id_p;

/// The product title associated with this service.
@property(nonatomic, readwrite, copy, null_resettable) NSString *title;

/// The id of the Google developer project that owns the service.
/// Members of this project can manage the service configuration,
/// manage consumption of the service, etc.
@property(nonatomic, readwrite, copy, null_resettable) NSString *producerProjectId;

/// A list of API interfaces exported by this service. Only the `name` field
/// of the [google.protobuf.Api][google.protobuf.Api] needs to be provided by the configuration
/// author, as the remaining fields will be derived from the IDL during the
/// normalization process. It is an error to specify an API interface here
/// which cannot be resolved against the associated IDL files.
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<GPBApi*> *apisArray;
/// The number of items in @c apisArray without causing the array to be created.
@property(nonatomic, readonly) NSUInteger apisArray_Count;

/// A list of all proto message types included in this API service.
/// Types referenced directly or indirectly by the `apis` are
/// automatically included.  Messages which are not referenced but
/// shall be included, such as types used by the `google.protobuf.Any` type,
/// should be listed here by name. Example:
///
///     types:
///     - name: google.protobuf.Int32
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<GPBType*> *typesArray;
/// The number of items in @c typesArray without causing the array to be created.
@property(nonatomic, readonly) NSUInteger typesArray_Count;

/// A list of all enum types included in this API service.  Enums
/// referenced directly or indirectly by the `apis` are automatically
/// included.  Enums which are not referenced but shall be included
/// should be listed here by name. Example:
///
///     enums:
///     - name: google.someapi.v1.SomeEnum
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<GPBEnum*> *enumsArray;
/// The number of items in @c enumsArray without causing the array to be created.
@property(nonatomic, readonly) NSUInteger enumsArray_Count;

/// Additional API documentation.
@property(nonatomic, readwrite, strong, null_resettable) Documentation *documentation;
/// Test to see if @c documentation has been set.
@property(nonatomic, readwrite) BOOL hasDocumentation;

/// API backend configuration.
@property(nonatomic, readwrite, strong, null_resettable) Backend *backend;
/// Test to see if @c backend has been set.
@property(nonatomic, readwrite) BOOL hasBackend;

/// HTTP configuration.
@property(nonatomic, readwrite, strong, null_resettable) Http *HTTP;
/// Test to see if @c HTTP has been set.
@property(nonatomic, readwrite) BOOL hasHTTP;

/// Auth configuration.
@property(nonatomic, readwrite, strong, null_resettable) Authentication *authentication;
/// Test to see if @c authentication has been set.
@property(nonatomic, readwrite) BOOL hasAuthentication;

/// Context configuration.
@property(nonatomic, readwrite, strong, null_resettable) Context *context;
/// Test to see if @c context has been set.
@property(nonatomic, readwrite) BOOL hasContext;

/// Configuration controlling usage of this service.
@property(nonatomic, readwrite, strong, null_resettable) Usage *usage;
/// Test to see if @c usage has been set.
@property(nonatomic, readwrite) BOOL hasUsage;

/// Configuration of per-consumer project properties.
@property(nonatomic, readwrite, strong, null_resettable) ProjectProperties *projectProperties;
/// Test to see if @c projectProperties has been set.
@property(nonatomic, readwrite) BOOL hasProjectProperties;

/// Configuration for the service control plane.
@property(nonatomic, readwrite, strong, null_resettable) Control *control;
/// Test to see if @c control has been set.
@property(nonatomic, readwrite) BOOL hasControl;

/// Defines the logs used by this service.
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<LogDescriptor*> *logsArray;
/// The number of items in @c logsArray without causing the array to be created.
@property(nonatomic, readonly) NSUInteger logsArray_Count;

/// Defines the metrics used by this service.
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<MetricDescriptor*> *metricsArray;
/// The number of items in @c metricsArray without causing the array to be created.
@property(nonatomic, readonly) NSUInteger metricsArray_Count;

/// Defines the monitored resources used by this service. This is required
/// by the [Service.monitoring][google.api.Service.monitoring] and [Service.logging][google.api.Service.logging] configurations.
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<MonitoredResourceDescriptor*> *monitoredResourcesArray;
/// The number of items in @c monitoredResourcesArray without causing the array to be created.
@property(nonatomic, readonly) NSUInteger monitoredResourcesArray_Count;

/// Billing configuration of the service.
@property(nonatomic, readwrite, strong, null_resettable) Billing *billing;
/// Test to see if @c billing has been set.
@property(nonatomic, readwrite) BOOL hasBilling;

/// Logging configuration of the service.
@property(nonatomic, readwrite, strong, null_resettable) Logging *logging;
/// Test to see if @c logging has been set.
@property(nonatomic, readwrite) BOOL hasLogging;

/// Monitoring configuration of the service.
@property(nonatomic, readwrite, strong, null_resettable) Monitoring *monitoring;
/// Test to see if @c monitoring has been set.
@property(nonatomic, readwrite) BOOL hasMonitoring;

/// Configuration for system parameters.
@property(nonatomic, readwrite, strong, null_resettable) SystemParameters *systemParameters;
/// Test to see if @c systemParameters has been set.
@property(nonatomic, readwrite) BOOL hasSystemParameters;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
