// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/api/service.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/Any.pbobjc.h>
 #import <Protobuf/Api.pbobjc.h>
 #import <Protobuf/Type.pbobjc.h>
 #import <Protobuf/Wrappers.pbobjc.h>
#else
 #import "google/protobuf/Any.pbobjc.h"
 #import "google/protobuf/Api.pbobjc.h"
 #import "google/protobuf/Type.pbobjc.h"
 #import "google/protobuf/Wrappers.pbobjc.h"
#endif

 #import "google/api/Service.pbobjc.h"
 #import "google/api/Annotations.pbobjc.h"
 #import "google/api/Auth.pbobjc.h"
 #import "google/api/Backend.pbobjc.h"
 #import "google/api/Billing.pbobjc.h"
 #import "google/api/Consumer.pbobjc.h"
 #import "google/api/Context.pbobjc.h"
 #import "google/api/Control.pbobjc.h"
 #import "google/api/Documentation.pbobjc.h"
 #import "google/api/HTTP.pbobjc.h"
 #import "google/api/Label.pbobjc.h"
 #import "google/api/Log.pbobjc.h"
 #import "google/api/Logging.pbobjc.h"
 #import "google/api/Metric.pbobjc.h"
 #import "google/api/MonitoredResource.pbobjc.h"
 #import "google/api/Monitoring.pbobjc.h"
 #import "google/api/SystemParameter.pbobjc.h"
 #import "google/api/Usage.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - ServiceRoot

@implementation ServiceRoot

+ (GPBExtensionRegistry*)extensionRegistry {
  // This is called by +initialize so there is no need to worry
  // about thread safety and initialization of registry.
  static GPBExtensionRegistry* registry = nil;
  if (!registry) {
    GPBDebugCheckRuntimeVersion();
    registry = [[GPBExtensionRegistry alloc] init];
    [registry addExtensions:[AnnotationsRoot extensionRegistry]];
    [registry addExtensions:[AuthRoot extensionRegistry]];
    [registry addExtensions:[BackendRoot extensionRegistry]];
    [registry addExtensions:[BillingRoot extensionRegistry]];
    [registry addExtensions:[ConsumerRoot extensionRegistry]];
    [registry addExtensions:[ContextRoot extensionRegistry]];
    [registry addExtensions:[ControlRoot extensionRegistry]];
    [registry addExtensions:[DocumentationRoot extensionRegistry]];
    [registry addExtensions:[HTTPRoot extensionRegistry]];
    [registry addExtensions:[LabelRoot extensionRegistry]];
    [registry addExtensions:[LogRoot extensionRegistry]];
    [registry addExtensions:[LoggingRoot extensionRegistry]];
    [registry addExtensions:[MetricRoot extensionRegistry]];
    [registry addExtensions:[MonitoredResourceRoot extensionRegistry]];
    [registry addExtensions:[MonitoringRoot extensionRegistry]];
    [registry addExtensions:[SystemParameterRoot extensionRegistry]];
    [registry addExtensions:[UsageRoot extensionRegistry]];
    [registry addExtensions:[GPBAnyRoot extensionRegistry]];
    [registry addExtensions:[GPBApiRoot extensionRegistry]];
    [registry addExtensions:[GPBTypeRoot extensionRegistry]];
    [registry addExtensions:[GPBWrappersRoot extensionRegistry]];
  }
  return registry;
}

@end

#pragma mark - ServiceRoot_FileDescriptor

static GPBFileDescriptor *ServiceRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPBDebugCheckRuntimeVersion();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"google.api"
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - Service

@implementation Service

@dynamic hasConfigVersion, configVersion;
@dynamic name;
@dynamic id_p;
@dynamic title;
@dynamic producerProjectId;
@dynamic apisArray, apisArray_Count;
@dynamic typesArray, typesArray_Count;
@dynamic enumsArray, enumsArray_Count;
@dynamic hasDocumentation, documentation;
@dynamic hasBackend, backend;
@dynamic hasHTTP, HTTP;
@dynamic hasAuthentication, authentication;
@dynamic hasContext, context;
@dynamic hasUsage, usage;
@dynamic hasProjectProperties, projectProperties;
@dynamic hasControl, control;
@dynamic logsArray, logsArray_Count;
@dynamic metricsArray, metricsArray_Count;
@dynamic monitoredResourcesArray, monitoredResourcesArray_Count;
@dynamic hasBilling, billing;
@dynamic hasLogging, logging;
@dynamic hasMonitoring, monitoring;
@dynamic hasSystemParameters, systemParameters;

typedef struct Service__storage_ {
  uint32_t _has_storage_[1];
  NSString *name;
  NSString *title;
  NSMutableArray *apisArray;
  NSMutableArray *typesArray;
  NSMutableArray *enumsArray;
  Documentation *documentation;
  Backend *backend;
  Http *HTTP;
  Authentication *authentication;
  Context *context;
  Usage *usage;
  ProjectProperties *projectProperties;
  GPBUInt32Value *configVersion;
  Control *control;
  NSString *producerProjectId;
  NSMutableArray *logsArray;
  NSMutableArray *metricsArray;
  NSMutableArray *monitoredResourcesArray;
  Billing *billing;
  Logging *logging;
  Monitoring *monitoring;
  SystemParameters *systemParameters;
  NSString *id_p;
} Service__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "name",
        .dataTypeSpecific.className = NULL,
        .number = Service_FieldNumber_Name,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(Service__storage_, name),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "title",
        .dataTypeSpecific.className = NULL,
        .number = Service_FieldNumber_Title,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(Service__storage_, title),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "apisArray",
        .dataTypeSpecific.className = GPBStringifySymbol(GPBApi),
        .number = Service_FieldNumber_ApisArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(Service__storage_, apisArray),
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "typesArray",
        .dataTypeSpecific.className = GPBStringifySymbol(GPBType),
        .number = Service_FieldNumber_TypesArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(Service__storage_, typesArray),
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "enumsArray",
        .dataTypeSpecific.className = GPBStringifySymbol(GPBEnum),
        .number = Service_FieldNumber_EnumsArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(Service__storage_, enumsArray),
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "documentation",
        .dataTypeSpecific.className = GPBStringifySymbol(Documentation),
        .number = Service_FieldNumber_Documentation,
        .hasIndex = 5,
        .offset = (uint32_t)offsetof(Service__storage_, documentation),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "backend",
        .dataTypeSpecific.className = GPBStringifySymbol(Backend),
        .number = Service_FieldNumber_Backend,
        .hasIndex = 6,
        .offset = (uint32_t)offsetof(Service__storage_, backend),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "HTTP",
        .dataTypeSpecific.className = GPBStringifySymbol(Http),
        .number = Service_FieldNumber_HTTP,
        .hasIndex = 7,
        .offset = (uint32_t)offsetof(Service__storage_, HTTP),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "authentication",
        .dataTypeSpecific.className = GPBStringifySymbol(Authentication),
        .number = Service_FieldNumber_Authentication,
        .hasIndex = 8,
        .offset = (uint32_t)offsetof(Service__storage_, authentication),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "context",
        .dataTypeSpecific.className = GPBStringifySymbol(Context),
        .number = Service_FieldNumber_Context,
        .hasIndex = 9,
        .offset = (uint32_t)offsetof(Service__storage_, context),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "usage",
        .dataTypeSpecific.className = GPBStringifySymbol(Usage),
        .number = Service_FieldNumber_Usage,
        .hasIndex = 10,
        .offset = (uint32_t)offsetof(Service__storage_, usage),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "projectProperties",
        .dataTypeSpecific.className = GPBStringifySymbol(ProjectProperties),
        .number = Service_FieldNumber_ProjectProperties,
        .hasIndex = 11,
        .offset = (uint32_t)offsetof(Service__storage_, projectProperties),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "configVersion",
        .dataTypeSpecific.className = GPBStringifySymbol(GPBUInt32Value),
        .number = Service_FieldNumber_ConfigVersion,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(Service__storage_, configVersion),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "control",
        .dataTypeSpecific.className = GPBStringifySymbol(Control),
        .number = Service_FieldNumber_Control,
        .hasIndex = 12,
        .offset = (uint32_t)offsetof(Service__storage_, control),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "producerProjectId",
        .dataTypeSpecific.className = NULL,
        .number = Service_FieldNumber_ProducerProjectId,
        .hasIndex = 4,
        .offset = (uint32_t)offsetof(Service__storage_, producerProjectId),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "logsArray",
        .dataTypeSpecific.className = GPBStringifySymbol(LogDescriptor),
        .number = Service_FieldNumber_LogsArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(Service__storage_, logsArray),
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "metricsArray",
        .dataTypeSpecific.className = GPBStringifySymbol(MetricDescriptor),
        .number = Service_FieldNumber_MetricsArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(Service__storage_, metricsArray),
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "monitoredResourcesArray",
        .dataTypeSpecific.className = GPBStringifySymbol(MonitoredResourceDescriptor),
        .number = Service_FieldNumber_MonitoredResourcesArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(Service__storage_, monitoredResourcesArray),
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "billing",
        .dataTypeSpecific.className = GPBStringifySymbol(Billing),
        .number = Service_FieldNumber_Billing,
        .hasIndex = 13,
        .offset = (uint32_t)offsetof(Service__storage_, billing),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "logging",
        .dataTypeSpecific.className = GPBStringifySymbol(Logging),
        .number = Service_FieldNumber_Logging,
        .hasIndex = 14,
        .offset = (uint32_t)offsetof(Service__storage_, logging),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "monitoring",
        .dataTypeSpecific.className = GPBStringifySymbol(Monitoring),
        .number = Service_FieldNumber_Monitoring,
        .hasIndex = 15,
        .offset = (uint32_t)offsetof(Service__storage_, monitoring),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "systemParameters",
        .dataTypeSpecific.className = GPBStringifySymbol(SystemParameters),
        .number = Service_FieldNumber_SystemParameters,
        .hasIndex = 16,
        .offset = (uint32_t)offsetof(Service__storage_, systemParameters),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "id_p",
        .dataTypeSpecific.className = NULL,
        .number = Service_FieldNumber_Id_p,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(Service__storage_, id_p),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[Service class]
                                     rootClass:[ServiceRoot class]
                                          file:ServiceRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(Service__storage_)
                                         flags:0];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\001\t!!!!\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
